# GE's own PET software, off the console and self-contained: pet_recon for the
# correction sinograms, librdf + the dragon list-mode tools for decode.
#
# ---------------------------------------------------------------------------
# THIS IS A RECORD OF HOW d710:full WAS MADE, NOT HOW YOU GET IT.
#
# The image is handed over as an image:
#
#   docker load -i d710_full.tar          # <- the normal path
#   docker image inspect d710:full        # <- how `d710` checks for it
#
# It cannot be rebuilt from a fresh checkout anyway: the COPY lines below reach
# into custom_tool/petsw/, 18 GB of console software that is not in this repo
# and is not redistributable.  Whoever holds that tree can rebuild, from the
# PROJECT ROOT so COPY can see it:
#
#   docker build -t d710:full -f D710/Dockerfile .
#
# Everything else about the image is described here so that what is inside it
# is readable without unpacking 7 GB.
# ---------------------------------------------------------------------------
#
#   d710 estimate --raw <SINO dir> --ct <CT> --case <n>   randoms/scatter/norm/dt
#   d710 decode   --raw <SINO dir> --case <n>             sinograms + list mode
#
# The image does NOT bake D710/'s own code.  `d710` bind-mounts this tree at
# /d710 (and vendor/ again at /vendor, because the gdb scripts source each
# other by absolute path), so editing a Python file or a gdb probe changes what
# the next run does -- no rebuild, which matters all the more when rebuilding
# is not on the table.  Only what cannot be mounted lives inside: GE's console
# tree and the decoder.
#
# The root .dockerignore cuts the 18 GB console tree down to the ~3.6 GB this
# image actually opens.  Without it docker ships all 18 GB to the daemon on
# every build, which is what the old bake.sh existed to dodge: it bind-mounted
# petsw/ into a throwaway container and `docker commit`ed the result.  That
# produced a complete, pushable image -- a commit is an ordinary image -- but
# nothing could REBUILD it, because the Dockerfile did not describe its
# contents.  .dockerignore fixes the context problem properly, so the copy can
# be an honest COPY and `docker push` ships something reproducible.
#
# pet_recon pins threads to CPUs 6-11 (coremap.cfg.parc3), so give the container
# at least 12 CPUs or the affinity calls fail noisily (not fatal).  gdb needs
# --cap-add=SYS_PTRACE.  run.sh handles both.

# ---------------------------------------------------------------------- base
# Toolchain only, no vendor tree -- NOT usable on its own.  run.sh --mount
# bind-mounts petsw/ from the host onto this as a fallback, so it stays a
# separate stage:
#   docker build --target base -t d710 -f D710/Dockerfile .
FROM debian:bookworm-slim AS base

RUN apt-get update && apt-get install -y --no-install-recommends \
        gdb python3 binutils libc6 libstdc++6 file procps \
    && rm -rf /var/lib/apt/lists/*

# The decode side is i386: GE's librdf.so.0 and the dragon list-mode tools
# (unglepl, rdfTell, rdfListDecode) are 32-bit x86, and they ride along inside
# /usr/PET at no extra cost, so the only thing missing is a loader for them.
# libstdc++6:i386 is for unglepl -- librdf needs libc alone.  Debian's i386
# libraries live in /usr/lib/i386-linux-gnu and cannot collide with GE's.
#
# gcc-multilib stays so the image can rebuild its own helper from rdfx.c; the
# full stage prebuilds it, so a decode run compiles nothing.
#
# petsird is pinned to the version the host env has, so a .prd written in here
# is the same file the host would have written.
RUN dpkg --add-architecture i386 \
    && apt-get update && apt-get install -y --no-install-recommends \
        gcc gcc-multilib libc6:i386 libstdc++6:i386 libgcc-s1:i386 \
        python3-numpy python3-scipy python3-pydicom python3-pip \
    && pip install --break-system-packages --no-cache-dir petsird==0.9.1 \
    && rm -rf /var/lib/apt/lists/*

# Only the five libraries pet_recon needs from the console's /usr/lib64 go here.
# The whole console /usr/lib64 must NOT land on a path gdb searches: GE's
# libstdc++ is far older than gdb's and stops gdb starting.  boot.gdb puts this
# on the *inferior's* LD_LIBRARY_PATH only.
ENV PETSW_VLIB=/vendorlib

# PETSW_ROOT=/ tells petsw_run.sh the console tree is already at its real paths,
# so it must skip the unprivileged-namespace dance it does on a host -- there is
# no CAP_SYS_ADMIN in a container and `unshare` fails outright.
ENV PETSW_ROOT=/ \
    GERDF_LIBRDF=/usr/PET/lib/linux2/librdf.so.0 \
    GERDF_RDFX=/opt/custom_tool/native/rdfx \
    PYTHONPATH=/opt/custom_tool

# 3D recon packets stream axial-overlap files through /petRDFS/OVLFILES.
RUN mkdir -p /petRDFS/OVLFILES /out /vendorlib

# NOTE: the console's hostnames (CT85_OC0, loghost, ...) cannot be baked in --
# /etc/hosts is generated by the daemon at run time, so a build-time write fails
# with exit 2.  They are passed as --add-host by run.sh.  Without them the
# startup path dies in gethostbyname before anything else is attempted.

WORKDIR /out

# ---------------------------------------------------------------------- full
FROM base AS full

# The console binaries open configuration by ABSOLUTE path, so the tree has to
# land on /usr/PET and /usr/g exactly.  systemConfig must be writable: the
# config manager opens cmcfg.xml read-write and dies otherwise.  service/log is
# excluded by .dockerignore (9.2 GB) but must exist -- pet_recon writes
# IG1.timers.log there.
#
# `u+w` and not `a+w` is why the pet_recon path runs as root while everything
# else runs as --user: systemConfig, /usr/g/service/log and /petRDFS/OVLFILES
# are all root-owned and root-writable only, and all three are written during
# a run.  See vendor/run.sh.
COPY custom_tool/petsw/usr/PET /usr/PET
COPY custom_tool/petsw/usr/g   /usr/g
RUN chmod -R u+w /usr/PET/systemConfig && mkdir -p /usr/g/service/log

COPY custom_tool/petsw/usr/lib64/libreadcfg.so* \
     custom_tool/petsw/usr/lib64/libeventmgr.so* \
     custom_tool/petsw/usr/lib64/libmsghand.so* \
     custom_tool/petsw/usr/lib64/libcupipc.so* \
     custom_tool/petsw/usr/lib64/libstartup.so* \
     /vendorlib/

# custom_tool's source, minus the vendor tree it no longer needs -- the /usr/PET
# copied above IS that tree, and gerdf reaches it by the console path.  Listed
# per directory rather than as one COPY of custom_tool/ so that petsw/ cannot
# be dragged in a second time.  Last, so editing gerdf rebuilds only this layer.
COPY custom_tool/gerdf          /opt/custom_tool/gerdf
COPY custom_tool/native         /opt/custom_tool/native
COPY custom_tool/tests          /opt/custom_tool/tests
COPY custom_tool/ge_rdf_tool.py custom_tool/README.md /opt/custom_tool/

# Built here rather than copied in: the host's rdfx is linked against the host
# loader, and this image has real multilib so build.sh takes its fast path.
# The final line is a smoke test -- it fails the build if librdf will not load,
# which is exactly how the missing -Wl,--export-dynamic showed up.
RUN cd /opt/custom_tool/native \
    && bash build.sh \
    && bash build_stubs.sh >/dev/null \
    && ./rdfx 2>&1 | grep -q 'usage: rdfx'
